### ISSUE TITLE
LXD often fails to refresh due to socket error

### ISSUE THREAD

**Issue by ghislainbourgeois** [jnsgruk/concierge#20]
When concierge needs to fresh LXD, it often fails because LXD fails on the configure hook with an error about the missing socket file: `/run/snapd-snap.socket`.

This is already known by the LXD team and the issue is not directly in concierge, but there is a known workaround to run `snap stop lxd` before executing the refresh.

I will be opening a PR to add this workaround soon.

**Comment by gruyaume** [comment]
We still seem to have those issues with concierge 0.9.3, even after merging the fix refered here. 

## Logs 
[concierge_bug_logs.txt](https://github.com/user-attachments/files/17836745/concierge_bug_logs.txt)


## Reference
- https://github.com/canonical/oai-ran-cu-k8s-operator/actions/runs/11940693676/job/33286704570
